version: "3.9"

services:
  db:
    container_name: db
    image: postgres:16.4
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: 'redis:alpine'
    hostname: redis

  django_app:
    container_name: django_app
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./sports_equipment_inventory:/sports_equipment_inventory
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
      - db

  celery:
    build: .
    command: celery -A sports_equipment_inventory worker -l info
    env_file:
      - .env
    volumes:
      - ./sports_equipment_inventory:/sports_equipment_inventory
    depends_on:
      - redis
  
  celery-beat:
    build: .
    command: celery -A sports_equipment_inventory beat -l info
    env_file:
      - .env
    depends_on:
      - redis


volumes:
  pgdata:
